### PR TITLE
2019.10+fio.secure.configs

### PR DESCRIPTION
**Pull request by ldts**
Create secure configs to enable the TA (FIOVB and OPTEE) on aeler's lmp and mfgtool configs; this gives uboot access to RPMB once the keys have been provisioned

### CODE REVIEW

**Comment by ldts** [comment]
I branched aelers lmp and mfgtool configs and enabled FIOVB and OPTEE so we can access the TA.

**Comment by ldts** [comment]
updated @mike-scott @ricardosalveti

**Comment by ldts** [comment]
this pull request will need devices to be configured in single boot mode (via dip switches). otherwise, uboot.itb with the M4 image embedded will cause the system not to boot due to failing upgrades

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
