### PR TITLE
[FIO extras] fiovb: return error on init if board not closed

### PR DESCRIPTION
**Pull request by Tim-Anderson**
Signed-off-by: Tim Anderson <tim.anderson@foundries.io>

Please do not submit a Pull Request via github.  Our project makes use of
mailing lists for patch submission and review.  For more details please
see https://www.denx.de/wiki/U-Boot/Patches

### CODE REVIEW

**Comment by igoropaniuk** [comment]
@Tim-Anderson I think that will break non-imx boards, and also imx7ulp, as `boot_mode_is_closed` is not defined for that boards

**Review by igoropaniuk — APPROVED** [review]
LGTM

**Comment by ricardosalveti** [comment]
> @Tim-Anderson I think that will break non-imx boards, and also imx7ulp, as `boot_mode_is_closed` is not defined for that boards

@Tim-Anderson can you make sure we also implement boot_mode_is_closed for 7ulp? Otherwise this will bite us as @vanmaegima updates 7ulp to the latest.

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
