### PR TITLE
Complete 2023.04+lf 6.1.22-2.0.0-fio

### PR DESCRIPTION
**Pull request by MrCry0**
- Porting commits: DONE
- Fixing major build issues: DONE

Update:
- drop one more commit
- fix crashing while checking the rsa hash in SPL

Tested building of all supported nxp boards:
https://app.foundries.io/factories/cryo-imx/targets/152/

@ricardosalveti The PR is ready to merge.

Here is the commits list with comments: https://docs.google.com/spreadsheets/d/12ZJVDFpnShWP97Yj2T0W2iytEzzLvKQj6EUl6XKsLZY/edit?usp=sharing

### CODE REVIEW

**Comment by ricardosalveti** [comment]
Some general comments by looking at the list of changes:

Can be squashed:
- Patches related to secondary boot can probably be squashed as they are all internal and easier to manage with less patches

Can be removed:
- [FIO toup] imx8mq_evk: define default dfu_alt_info for emmc updates (needed for SR, but it might not be the best solution for this base version)
- [FIO toup] imx8mm_evk: define default dfu_alt_info for emmc updates (same)
- [FIO toup] imx8mn_evk: define default dfu_alt_info for emmc updates (same)
- Patches for mx7ulp_com should also be removed and handled separately (via meta-partner for EA)
- SPL related changes (size reduction for allowing USB support on iMX8 targets) can probably be removed as well, as with mfgtools we can use the larger boot binary instead of breaking into SPL + u-boot.itb
- [FIO toup] apalis-imx8: allow dropping CONFIG_CMD_USB requirement (toradex partner layer?)

**Comment by ricardosalveti** [comment]
Will do some testing now.

**Comment by MrCry0** [comment]
> Will do some testing now.

@ricardosalveti Sure, you can find the draft of changes in configs there: https://github.com/MrCry0/meta-lmp/tree/main-u-boot-2023.04

**Comment by MrCry0** [comment]
> Some general comments by looking at the list of changes:
> 
> Can be squashed:
> 
> * Patches related to secondary boot can probably be squashed as they are all internal and easier to manage with less patches

Squashed most of the secondary boot work to 2 commits.


> Can be removed:
> 
> * [FIO toup] imx8mq_evk: define default dfu_alt_info for emmc updates (needed for SR, but it might not be the best solution for this base version)
> * [FIO toup] imx8mm_evk: define default dfu_alt_info for emmc updates (same)
> * [FIO toup] imx8mn_evk: define default dfu_alt_info for emmc updates (same)

Done.

> * Patches for mx7ulp_com should also be removed and handled separately (via meta-partner for EA)

Dropped.

> * SPL related changes (size reduction for allowing USB support on iMX8 targets) can probably be removed as well, as with mfgtools we can use the larger boot binary instead of breaking into SPL + u-boot.itb

Should we replace the mfgtool u-boot scheme for the coming release? I would prefer to have meta-lmp stuff for this in place before removing u-boot stuff.

> * [FIO toup] apalis-imx8: allow dropping CONFIG_CMD_USB requirement (toradex partner layer?)

Dropped.

**Comment by ricardosalveti** [comment]
> Should we replace the mfgtool u-boot scheme for the coming release? I would prefer to have meta-lmp stuff for this in place before removing u-boot stuff.

Yeah, let's switch meta-lmp first and then remove from this list (we can always revert and on the next rebase we drop them all).

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
