### PR TITLE
[FIO extras] armv7: Kconfig: route reset to PSCI

### PR DESCRIPTION
**Pull request by ldts**
Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>

Please do not submit a Pull Request via github.  Our project makes use of
mailing lists for patch submission and review.  For more details please
see https://www.denx.de/wiki/U-Boot/Patches

### CODE REVIEW

**Comment by ldts** [comment]
preparation for xrdc

**Comment by ldts** [comment]
this is required if we end up having xrdc in optee but even if it isnt, seems saner to route all resets to the  TEE.

**Comment by ricardosalveti** [comment]
Wouldn't this be toup (for upstreaming)? I agree that this is a safe assumption if PSCI is available.

Would this have any side effect on a possible SPL reset? As PSCI is not available there, just for u-boot proper.

**Comment by ldts** [comment]
I did test it and psci is not compiled in with SPL so it wont be an issue (it will default to the non-psci case)

**Comment by ldts** [comment]
I guess it doesnt matter....will just keep it on my tree. anyway is just uboot reset.

**Pull request closed without merging**
