### PR TITLE
Forward port FIO commits to 2021.04+imx 5.10.35 2.0.0 #1

### PR DESCRIPTION
**Pull request by MrCry0**
There is a 1st part of FIO commits ported from 2020.04+imx_5.4.70_2.3.0-fio to 2021.04+imx_5.10.35-2.0.0-fio.

Commits' status tracks in the following document: https://docs.google.com/spreadsheets/d/1SZGSN0I6J1jJdqiHJT1vDllIhRsDogUC5gK0D8XhGlw/edit?usp=sharing

Only build tests completed so far.

Please do not submit a Pull Request via github.  Our project makes use of
mailing lists for patch submission and review.  For more details please
see https://www.denx.de/wiki/U-Boot/Patches

### CODE REVIEW

**Comment by ricardosalveti** [comment]
- [FIO fromlist] cmd: Add CONFIG_FIT_SIGNATURE_STRICT

Seems to be incomplete (just changing common/Kconfig.boot). I saw you said you would rework based on Igor's review, maybe that is why?

**Comment by ricardosalveti** [comment]
- [FIO extras] rpi: prefer downstream dtb files

This one we can drop now as we're not using the device tree from the fit image anymore on rpi (we're now consuming the device tree that gets produced/populated by the proprietary firmware).

**Comment by ricardosalveti** [comment]
- [FIO toup] mx6cuboxi: only check for eMMC if som is at least 1.5

This one we can drop as we don't really support/test cubox-i anymore (less things to maintain).

**Comment by ricardosalveti** [comment]
Other than these comments, things seems fine. Thanks a lot for cleaning up the patches and upstreaming a few, things are looking a bit better already.

**Comment by MrCry0** [comment]
> * [FIO extras] rpi: prefer downstream dtb files
> 
> This one we can drop now as we're not using the device tree from the fit image anymore on rpi (we're now consuming the device tree that gets produced/populated by the proprietary firmware).

@ricardosalveti Interesting, I even marked it in the list as dropped but forgot to it in real :)
Thanks!

**Comment by MrCry0** [comment]
> * [FIO fromlist] cmd: Add CONFIG_FIT_SIGNATURE_STRICT
> 
> Seems to be incomplete (just changing common/Kconfig.boot). I saw you said you would rework based on Igor's review, maybe that is why?

@ricardosalveti thanks, fixed. There was also another review for the SPL part and satisfying that reviewer would be not easy :)
I postponed reworking that patchset for a while.

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
