### PR TITLE
Imx7ulp hwlock

### PR DESCRIPTION
**Pull request by ldts**
Please do not submit a Pull Request via github.  Our project makes use of
mailing lists for patch submission and review.  For more details please
see https://www.denx.de/wiki/U-Boot/Patches

### CODE REVIEW

**Comment by ldts** [comment]
Required for Aeler where QSPI needs to be owned by the A7 during boot (or reset) to determine if it needs to flash a new version of the M4. Once done, it gives control back to the M4 until the next reset...

**Comment by ricardosalveti** [comment]
Seems fine, will let this one for @mike-scott.

**Review by mike-scott — COMMENTED** [review]
These changes are definitely working for my testing.

I have rebooted the A7 several times and have not experience any QSPI locks.

There is something at play with the M4 code changes that has stopped several re-occurring tasks from working correctly.   Will discuss privately.

**Comment by ldts** [comment]
I think we should merge this and fix any issues as they come. this commit just implements a handshake whenever qspi is shared with the m4.

**Comment by mike-scott** [comment]
@ldts  is this the latest version of this PR?
We should merge this for historical reasons.  It's been tested.

**Comment by ldts** [comment]
@mike-scott yes it is the latest and it makes sense to me to keep something like this. I am sure similar needs are going to happen in the future.
I could try up-streaming to u-boot a generic interface for imx if we think it makes sense to invest the time.

**Pull request merged**
