### PR TITLE
U-boot 2022.04+lf 5.15.32-2.0.0-fio

### PR DESCRIPTION
**Pull request by MrCry0**
This is not yet tested.

### CODE REVIEW

**Comment by ricardosalveti** [comment]
* `[FIO toimx] imx7d: allow overriding reset_cpu()`
   - we can drop as we don't support colibri anymore
*  `[FIO internal] ti: add default implementation of mmc_map_to_kernel_blk()`
   - do we still need it? beagle is already using 2022.04 without extra patches.
* `[FIO internal] common: foundries.io verified boot utility`
   - we can squash `[FIO internal] common: FIOVB: split SPL config out`, `[FIO extras] fiovb: add support to delete persistent values`, `[FIO extras] fiovb: sync ta header for upgrade_available support`, `[FIO extras] fiovb: convert to cmd_tbl`, `[FIO extras] fiovb: return error on init if board not closed`, `[FIO internal] cmd: fiovb: increase fiovb_name buffer`, `[FIO squash] common: fix comment style in fiovb` as part of it (to reduce the amount of patches)
* `[FIO fromlist] spl: Add CONFIG_SPL_FIT_SIGNATURE_STRICT`
   - we can squash `[FIO toup] spl: spl_fit: fix hang() implicit declaration` and `[FIO toup] spl: spl_fit: add explicit braces` into it.
* `[FIO toup] imx7ulp: fiohab: support tool to enable closing the device`
   - we can squash `[FIO toup] imx6: fiohab: add handling for imx6`, `[FIO toup] arch: mach-imx: fiohab: use fiohab_dev var in fiovb_provisioned`, `[FIO extras] imx: fiohab: convert to cmd_tbl`, `[FIO extras] imx: fiohab: add support for IMX8MM`, `[FIO hack] imx: fiohab: ignore known HAB events`, `[FIO internal] imx: fiohab: add support for ahab`, `[FIO internal] arch: arm: mach-imx: fiohab: extend hab event message` into it

We can squash any other commit which you think that makes sense as well.

LGTM on the series, please squash the changes as we should be gtg.

**Comment by ricardosalveti** [comment]
Can you also bring the patches from https://github.com/foundriesio/u-boot/pull/156?

**Comment by MrCry0** [comment]
> Can you also bring the patches from #156?

Ok, that make sense.

**Comment by MrCry0** [comment]
> * `[FIO toimx] imx7d: allow overriding reset_cpu()`
>   
>   * we can drop as we don't support colibri anymore
> * `[FIO internal] ti: add default implementation of mmc_map_to_kernel_blk()`
>   
>   * do we still need it? beagle is already using 2022.04 without extra patches.
> * `[FIO internal] common: foundries.io verified boot utility`
>   
>   * we can squash `[FIO internal] common: FIOVB: split SPL config out`, `[FIO extras] fiovb: add support to delete persistent values`, `[FIO extras] fiovb: sync ta header for upgrade_available support`, `[FIO extras] fiovb: convert to cmd_tbl`, `[FIO extras] fiovb: return error on init if board not closed`, `[FIO internal] cmd: fiovb: increase fiovb_name buffer`, `[FIO squash] common: fix comment style in fiovb` as part of it (to reduce the amount of patches)
> * `[FIO fromlist] spl: Add CONFIG_SPL_FIT_SIGNATURE_STRICT`
>   
>   * we can squash `[FIO toup] spl: spl_fit: fix hang() implicit declaration` and `[FIO toup] spl: spl_fit: add explicit braces` into it.
> * `[FIO toup] imx7ulp: fiohab: support tool to enable closing the device`
>   
>   * we can squash `[FIO toup] imx6: fiohab: add handling for imx6`, `[FIO toup] arch: mach-imx: fiohab: use fiohab_dev var in fiovb_provisioned`, `[FIO extras] imx: fiohab: convert to cmd_tbl`, `[FIO extras] imx: fiohab: add support for IMX8MM`, `[FIO hack] imx: fiohab: ignore known HAB events`, `[FIO internal] imx: fiohab: add support for ahab`, `[FIO internal] arch: arm: mach-imx: fiohab: extend hab event message` into it
> 
> We can squash any other commit which you think that makes sense as well.
> 
> LGTM on the series, please squash the changes as we should be gtg.

Thanks for the feedback!
Squashing as much as can.

**Comment by MrCry0** [comment]
> Thanks for the feedback! Squashing as much as can.

@ricardosalveti Done.

**Comment by MrCry0** [comment]
Fixed the imx8mm updating issue.

**Comment by MrCry0** [comment]
> Can you also bring the patches from #156?

@ricardosalveti Done.

**Review by ricardosalveti — APPROVED** [review]
LGTM, looks sane, we can merge and start doing a wider testing with it.

**Pull request merged**
