### PR TITLE
Zynqmp fixes

### PR DESCRIPTION
**Pull request by igoropaniuk**
Please do not submit a Pull Request via github.  Our project makes use of
mailing lists for patch submission and review.  For more details please
see https://www.denx.de/wiki/U-Boot/Patches

### CODE REVIEW

**Review by MrCry0 — CHANGES_REQUESTED** [review]
_**[FIO toup] zynqmp: do_multi_boot: fix error output:**_
Could you use [FIO toup-squash] tag and add proper Fixes: field for its commit message. Thanks!

**Comment by igoropaniuk** [comment]
@MrCry0 fixed, thanks

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by vanmaegima — APPROVED** [review]
LGTM

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Pull request merged**
