### PR TITLE
Spl hw watchdog

### PR DESCRIPTION
**Pull request by igoropaniuk**
Please do not submit a Pull Request via github.  Our project makes use of
mailing lists for patch submission and review.  For more details please
see https://www.denx.de/wiki/U-Boot/Patches

### CODE REVIEW

**Comment by ricardosalveti** [comment]
@Tim-Anderson can you see if this fixes the issue you had?

**Comment by Tim-Anderson** [comment]
This worked in creating a imx6ullevk image in current head of lmp. It did
not work (i.e. did not build) when applied to the customer image. In
neither case did I try to boot or run it.

**Review by Tim-Anderson — APPROVED** [review]
From LMP this is good, LGTM

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
