### PR TITLE
Qspi flash

### PR DESCRIPTION
**Pull request by ldts**

### CODE REVIEW

**Comment by ricardosalveti** [comment]
Mind changing both commit messages to add the "[FIO extras]" tag as part of the subject? This is to easily know if the patch is a backport, something that we need to upstream or if something downstream specific.

**Comment by ricardosalveti** [comment]
Mike's commit is missing sign-off.

**Comment by ldts** [comment]
ok

**Review by mike-scott — APPROVED** [review]
LGTM

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
