### PR TITLE
Imx8qm mek fixes

### PR DESCRIPTION
**Pull request by igoropaniuk**
Please do not submit a Pull Request via github.  Our project makes use of
mailing lists for patch submission and review.  For more details please
see https://www.denx.de/wiki/U-Boot/Patches

### CODE REVIEW

**Comment by ricardosalveti** [comment]
[imx8: select HAS_CAAM only if HAS_CAAM is selected]

Commit should be only if OPTEE is not selected?

**Comment by igoropaniuk** [comment]
@ricardosalveti fixed

**Review by MrCry0 — APPROVED** [review]
LGTM

**Comment by ricardosalveti** [comment]
> @ricardosalveti fixed

Only if *not* selected, right?

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
