### PR TITLE
Porting FIO commits to mainline u-boot 2023.04

### PR DESCRIPTION
**Pull request by MrCry0**
Testing results:

- Building u-boot-fio recipe in LmP:
  - beaglebone-yocto: OK
  - qemuriscv64: OK
  - qemuarm64: OK
  - qemuarm : OK
  - stm32mp15-eval: OK
  - stm32mp15-disco: OK
  - raspberrypi4-64: OK

### CODE REVIEW

**Comment by ricardosalveti** [comment]
I don't expect any surprise here, but it would be good to have this validated on the stm32 platforms (@igoropaniuk ).

**Comment by MrCry0** [comment]
> I don't expect any surprise here, but it would be good to have this validated on the stm32 platforms (@igoropaniuk ).

I even have some building issues (for rpi and some stm32's), so I need to fix them before passing it to Igor :)

**Comment by MrCry0** [comment]
> I don't expect any surprise here, but it would be good to have this validated on the stm32 platforms (@igoropaniuk ).

@ricardosalveti I've fixed building for stm32*

@igoropaniuk could you please test this u-boot on a stm32 board?

**Comment by igoropaniuk** [comment]
@MrCry0 @ricardosalveti I'm seeing U-Boot hang during USB boot (for flashing):

```
U-Boot 2023.04+fio+g223303826b (Oct 27 2023 - 14:59:55 +0000)

NOTICE:  CPU: STM32MP157FAC Rev.Z
NOTICE:  Model: STMicroelectronics STM32MP157C-DK2 Discovery Board
NOTICE:  Board: MB1272 Var4.0 Rev.C-03
NOTICE:  BL2: v2.7(release):v2.7.0-dirty
NOTICE:  BL2: Built : 15:02:46, Jun  1 2022
NOTICE:  BL2: Booting BL32
I/TC: Early console on UART#4
I/TC: 
I/TC: Pager is enabled. Hashes: 3232 bytes
I/TC: Pager pool size: 96kB
I/TC: Non-secure external DT found
I/TC: Embedded DTB found
I/TC: OP-TEE version: 3.20.0-47-gaca0ad781+fio (gcc version 11.4.0 (GCC)) #1 Thu Aug 31 14:55:21 UTC 2023 arm
I/TC: WARNING: This OP-TEE configuration might be insecure!
I/TC: WARNING: Please check https://optee.readthedocs.io/en/latest/architecture/porting_guidelines.html
I/TC: Primary CPU initializing
I/TC: Platform stm32mp1: flavor 157C_DK2 - DT stm32mp157c-dk2.dts
I/TC: Non-secure SYSRAM [0x2ffbf000 0x2ffbffff]
I/TC: DTB enables console (non-secure)
I/TC: Non-secure external DT found
I/TC: Primary CPU switching to normal world boot
I/TC: Reserved shared memory is enabled
I/TC: Dynamic shared memory is enabled
I/TC: Normal World virtualization support is disabled
I/TC: Asynchronous notifications are disabled
optee optee: OP-TEE: revision 3.20 (aca0ad78)


U-Boot 2023.04+fio+g223303826b (Oct 27 2023 - 14:59:55 +0000)
```

with enabled full debug:
```
U-Boot 2023.04+fio+g223303826b (Nov 01 2023 - 11:44:01 +0000)

OF: translating address: 00000250
OF: parent translation for: 00000000
OF: one level translation: 00000250
pinctrl_stm32 pinctrl@54004000: hwspinlock_get_by_index: dev_read_phandle_with_args: err=-2
pinctrl_stm32 pinctrl@54004000: hwspinlock_get_by_index may have failed (-2)
OF: translating address: 00000000
OF: parent translation for: 00400054
OF: one level translation: 00400054
OF: parent translation for: 00000000
OF: one level translation: 00400054
gpio_stm32 gpio@54004000: addr = 0x54004000 bank_name = GPIOZ gpio_count = 16 gpio_range = 0xff

```


I'll debug it today

**Review by igoropaniuk — APPROVED** [review]
LGTM

**Pull request merged**
