### PR TITLE
Add support for i.MX6UL-EVK

### PR DESCRIPTION
**Pull request by mike-scott**
This patch series adds support for using i.MX6UL-EVK with our FIO-based changes in u-boot.

### CODE REVIEW

**Comment by mike-scott** [comment]
@MrCry0 Once approved, I can setup the same PR for the 2021.04 branch.

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by vanmaegima — APPROVED** [review]
LGTM

**Pull request merged**
