### PR TITLE
[RFC] 2022.04+lf 6.1.1 1.0.0-fio: fix boot area size

### PR DESCRIPTION
**Pull request by MrCry0**
Extend the size of bootloader2 partition for all i.MX-based boards.

### CODE REVIEW

**Comment by ricardosalveti** [comment]
Do we know why the size increased this much?

Maybe a side effect of the SR related config updates, which we might not really want in?

**Comment by MrCry0** [comment]
> Do we know why the size increased this much?
> 
> Maybe a side effect of the SR related config updates, which we might not really want in?

@ricardosalveti Do you mean KASLR or something else? Disabling KASLR feature saves about 1k only :(

There are a lot of drivers replaced by DM model-based and they bring the most size increase. For a long time, we suffer from the boot area size and we do a lot of effort to fit the u-boot image to 0x20000. I think it's time to solve the issue for some years in advance.

**Comment by MrCry0** [comment]
> Do we know why the size increased this much?
> 
> Maybe a side effect of the SR related config updates, which we might not really want in?

@ricardosalveti Hm. I revised syms and realized the new procedures are not as big. Need to investigate what larges the new u-boot to 400k.

**Comment by ricardosalveti** [comment]
What I find interesting is that this BSP tag is not really that different from the previous one, so curious what could have caused the size differences here.

Looking at the diff it seems KASLR was indeed the major config that changed. We also see some DM_RNG and RTC, but not sure if that would cause the size to increase too much.

**Comment by MrCry0** [comment]
Solved the issue by tuning configs for lmp-base.

**Pull request closed without merging**
