### PR TITLE
Stm32mp15 optee node fixes

### PR DESCRIPTION
**Pull request by igoropaniuk**
Please do not submit a Pull Request via github.  Our project makes use of
mailing lists for patch submission and review.  For more details please
see https://www.denx.de/wiki/U-Boot/Patches

The only exception to this is in order to trigger a CI loop on Azure prior
to posting of patches.

### CODE REVIEW

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Review by mike-scott — APPROVED** [review]
LGTM.  Thank you for fixing this.

**Comment by igoropaniuk** [comment]
Depends on https://github.com/foundriesio/meta-lmp/issues/919

**Review by vanmaegima — APPROVED** [review]

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
