### PR TITLE
[FIO toup] fiohab: mx7ulp: validate the M4 fuses

### PR DESCRIPTION
**Pull request by ldts**
Validate the M4 fuses before closing the board (not only the A7 ones)

Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>

Please do not submit a Pull Request via github.  Our project makes use of
mailing lists for patch submission and review.  For more details please
see https://www.denx.de/wiki/U-Boot/Patches

### CODE REVIEW

**Comment by ldts** [comment]
this should be merged in a release together with https://source.foundries.io/factories/aeler/meta-subscriber-overrides.git/log/?h=close-uuu

**Review by mike-scott — APPROVED** [review]
LGTM

**Comment by mike-scott** [comment]
@ricardosalveti Please review

**Comment by ldts** [comment]
@ricardosalveti ping

**Review by ricardosalveti — APPROVED** [review]

**Pull request merged**
