### PR TITLE
Revert cid

### PR DESCRIPTION
**Pull request by ldts**
Please do not submit a Pull Request via github.  Our project makes use of
mailing lists for patch submission and review.  For more details please
see https://www.denx.de/wiki/U-Boot/Patches

### CODE REVIEW

**Comment by ricardosalveti** [comment]
Can you add '[FIO fromlist]' as part of the commit subject at your second patch?

This is just to know that this patch was already submitted upstream.

**Comment by ldts** [comment]
sure I can do that but the patch has been acked already so maybe there is no need?

**Comment by ricardosalveti** [comment]
> sure I can do that but the patch has been acked already so maybe there is no need?

This is just to help when we migrate to a newer release, as then we can easily find the origin of the patch.

**Comment by ldts** [comment]
sure I understand that but my point is that the commit will be merged as is since it has been acked and reviewed (so we dont need to follow up further) ...ie, it will be on the release anyway along with all the other uboot files and we shouldnt need to worry about it. anyway it costs me nothing to resend so will do....

**Comment by ricardosalveti** [comment]
I agree that in the end it will be easy to find out, but better to have a tag for all the patches we add on top as that facilitates the job later on when rebasing it.

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
