### PR TITLE
Fixes for 2022.04+lf 5.15.52-2.1.0-fio

### PR DESCRIPTION
**Pull request by MrCry0**
Required fixes to use this branch as default for imx-2022.04:
- 0fa57cdba87 Revert "[FIO internal] fiovb: simplify code"
- 2800a589d83 [FIO squash] drivers: tee: i2c: fix format arguments size

### CODE REVIEW

**Comment by ricardosalveti** [comment]
Not sure I follow the need for the revert. Do we need to also revert the same patch from the other branches?

**Comment by MrCry0** [comment]
> Not sure I follow the need for the revert. Do we need to also revert the same patch from the other branches?

No, we don't need to revert this commit on `2022.04+fio` as these functions are used only in the imx u-boot versions
```
arch/arm/mach-imx/fiohab.c:	sec = fiovb_ops_alloc(fiohab_dev);
drivers/fpga/imx_m4.c:	sec = fiovb_ops_alloc(0);
```

So that the commit `"[FIO internal] fiovb: simplify code"` leads to build errors in `imx-2022.04`.

**Comment by ricardosalveti** [comment]
Argh, makes sense, forgot those.

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
